before_script:
  - chmod +x gradlew

mock:
  script:
    - ./gradlew clean coverageMockDebug sonarqube --stacktrace
  tags:
    - android
    - latest
  only:
    - master

dev:
  script:
    - ./gradlew clean assembleDevDebug sonarqube --stacktrace
  tags:
    - android
    - latest
  only:
    - develop

hockey:
  script:
    - /usr/bin/draw-version -d app/src/main/res -f ic_launcher.png
    - CHANGELOG=$(/usr/bin/changelog) ./gradlew clean uploadDevReleaseToHockeyApp
  tags:
    - android
    - build-tools-latest
  only:
    - /^v.*$/
