live:
  script:
    - CHANGELOG=$(/usr/bin/changelog) gradle clean lintProdLive uploadProdLiveToHockeyApp --stacktrace
  tags:
    - android
    - ubuild
  only:
    - /^v[\d.]+-live$/
  artifacts:
    expire_in: 2 week
    paths:
      - app/build/outputs/apk/*.apk
      - app/build/outputs/mapping

hockey:
  script:
    - /usr/bin/draw-version -d app/src/main/res -f ic_launcher.png
    - CHANGELOG=$(/usr/bin/changelog) gradle clean lintProdRelease uploadProdReleaseToHockeyApp --stacktrace
  tags:
    - android
    - ubuild
  only:
    - /^v[\d.]+$/

checkstyle:
  script:
    - gradle checkstyle findbugs pmd lintProdRelease
  tags:
    - android
    - ubuild
  except:
    - master
    - dev
    - /^v[\d.]+$/
    - /^v[\d.]+-live$/
  artifacts:
    when: on_failure
    paths:
      - app/build/reports/checkstyle/checkstyle.html
      - app/build/reports/findbugs/findbugs.html
      - app/build/reports/pmd/pmd.html
      - app/build/reports/lint-results-prodRelease.html
