release:
  script:
    - CHANGELOG=$(/usr/bin/changelog) gradle clean lintRelease assembleRelease crashlyticsUploadDistributionRelease --stacktrace
  tags:
    - android
    - ubuild
  only:
    - /^v[\d.]+r$/
  artifacts:
    expire_in: 2 week
    paths:
      - app/build/outputs/apk/*.apk
      - app/build/outputs/mapping

releaseQa:
  script:
    - CHANGELOG=$(/usr/bin/changelog) gradle clean lintReleaseQa assembleReleaseQa crashlyticsUploadDistributionReleaseQa --stacktrace
  tags:
    - android
    - ubuild
  only:
    - /^v[\d.]+t$/

verification:
  script:
    - gradle clean ktlint detektCheck testDebugUnitTest
  tags:
    - android
    - ubuild
  except:
    - master
    - dev
    - /^v[\d.]+t$/
    - /^v[\d.]+r$/
  artifacts:
    when: on_failure
    paths:
      - app/build/reports/checkstyle/checkstyle.html
      - app/build/reports/findbugs/findbugs.html
      - app/build/reports/pmd/pmd.html
      - app/build/reports/lint-results-debug.html
      - app/build/reports/tests/testDebugUnitTest/
