mock:
  script:
    - gradle clean jacocoUnitTestReport sonarqube --stacktrace
  tags:
    - android
    - latest
  only:
    - master

dev:
  script:
    - gradle clean assembleDevDebug
    - gradle sonarqube
  tags:
    - android
    - latest
  only:
    - develop

hockey:
  script:
    - /usr/bin/draw-version -d app/src/main/res -f ic_launcher.png
    - CHANGELOG=$(/usr/bin/changelog) gradle clean uploadDevReleaseToHockeyApp
  tags:
    - android
    - build-tools-latest
  only:
    - /^v.*$/
